### ISSUE TITLE
config file change via API does not save it in mediamtx.yml

### ISSUE THREAD

**Issue by QwertyAzerY** [bluenviron/mediamtx#3918] opened 2024-10-27 15:07 UTC
### Which version are you using?

1.9.1

### Which operating system are you using?

Linux arm64 standard

### Describe how to replicate the issue

1. Start the server
2. Patch config file via API
3. cat /usr/local/etc/mediamtx.ylm - shows unupdated config
But if you request config from API it will return updated version. 
4. If you restart service server will load old .yml file
file on disk didnt changed even if you have response 200 from API. 
Log says server reloaded config from API request. 
Maybe I'm stupid, and the file on the disk should not change when the config is changed via the API. Couldn't find this in the readme. In any case, I think this is a bug because when the service is restarted, the server uses a .yml file that has not been modified.

### Server logs

Oct 27 14:36:09 instance-Arm20231027-1224 systemd[1]: Started mediamtx.service.
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF MediaMTX v1.9.1
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF configuration loaded from /usr/local/etc/mediamtx.yml
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF [metrics] listener opened on :9998
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF [pprof] listener opened on :9999
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF [RTSP] listener opened on :57554 (TCP), :57000 (UDP/RTP), :57001 (UDP/RTCP)
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF [RTMP] listener opened on :57935
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF [HLS] listener opened on :57888
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF [WebRTC] listener opened on :57889 (HTTP), :57189 (ICE/UDP)
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF [SRT] listener opened on :57890 (UDP)
Oct 27 14:36:09 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:09 INF [API] listener opened on :9997
Oct 27 14:36:45 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:45 INF reloading configuration (API request)
Oct 27 14:36:45 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:45 INF [API] listener is closing
Oct 27 14:36:45 instance-Arm20231027-1224 mediamtx[827408]: 2024/10/27 14:36:45 INF [API] listener opened on :9997

**Comment by aler9** [comment] 2024-10-27 15:15
duplicate of #1406

**Closed by aler9** 2024-10-27 15:15 UTC
