### ISSUE TITLE
AV1 over rtsp gives a 400

### ISSUE THREAD

**Issue by reluekiss** [bluenviron/mediamtx#3340] opened 2024-05-08 14:49 UTC
## Which version are you using?

v1.4.2

## Which operating system are you using?

- [x] Linux arm64 standard

## Describe the issue

When streaming to the server with ffmpeg using the following commmand:
```
ffmpeg -re -i "$1" -c copy -loglevel debug -strict experimental -f rtsp "rtsp://user:streamkey@localhost:8890/mystream"
```
Will allow me stream without any issues, except when I try to stream AV1 video. Regardless of the container being used (mp4 or mkv), in the documentation it seemed as if rtsp had compatability for the AV1 codec.

## Describe how to replicate the issue

1. start the server
2. publish with the above ffmpeg code any AV1 encoded video
3. read with hls, or any other transport protocol.

## Did you attach the server logs?

Server logs with debugging on:
https://pastebin.com/nTwPZgB3
ffmpeg logs with debugging on:
https://pastebin.com/KQw0DC13

Yes

## Did you attach a network dump?

Not needed as it didn't work on localhost.

No

**Comment by aler9** [comment] 2024-05-08 16:03
This is a duplicate of #2261 and has been already answered there. Please use the search function before opening a new issue.

**Closed by aler9** 2024-05-08 16:03 UTC
