### ISSUE TITLE
Crash in ServerHTTP / webRTCHTTPServer

### ISSUE THREAD

**Issue by RogerDavenport** [bluenviron/mediamtx#2819] opened 2023-12-17 19:52 UTC
## Which version are you using?

v1.2.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [X] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

We run a system with 20+ webrtc streams, pulling video from RTSP cameras.  Streams are added through the HTTP API.

## Describe how to replicate the issue

Create lots of WebRTC sessions, open and close them.

## Did you attach the server logs?

YES

## Did you attach a network dump?

NO
[rtsp-crash.log](https://github.com/bluenviron/mediamtx/files/13697572/rtsp-crash.log)

**Comment by aler9** [comment] 2023-12-18 09:13
Hello, this is a duplicate of #2609, fixed with #2613, fixed since v1.3.0.

**Closed by aler9** 2023-12-18 09:13 UTC
