### ISSUE TITLE
Docker RTMPS server not work when gstreamer push stream

### ISSUE THREAD

**Issue by renyongjian** [bluenviron/mediamtx#2187] opened 2023-08-09 12:06 UTC
## Which version are you using?

v1.0.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [x ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1.  I changed configure file  like :
```
###############################################
# RTMP parameters

# Enable support for the RTMP protocol.
rtmp: yes
# Address of the RTMP listener. This is needed only when encryption is "no" or "optional".
rtmpAddress: :1935
# Encrypt connections with TLS (RTMPS).
# Available values are "no", "strict", "optional".
rtmpEncryption: "optional"
# Address of the RTMPS listener. This is needed only when encryption is "strict" or "optional".
rtmpsAddress: :1936
# Path to the server key. This is needed only when encryption is "strict" or "optional".
# This can be generated with:
# openssl genrsa -out server.key 2048
# openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
rtmpServerKey: /server.key
# Path to the server certificate. This is needed only when encryption is "strict" or "optional".
rtmpServerCert: /server.crt
```
2. I try to run server with cmd:
```
sudo docker run --rm -it --network=host \
-e MTX_PROTOCOLS=tcp \
-p 1936:1936 \
-v /home/mediamtx/mediamtx.yml:/mediamtx.yml \
-v /home/mediamtx/server.crt:/server.crt \
-v /home/mediamtx/server.key:/server.key \
bluenviron/mediamtx
```
3. then I try to push stream with gstreamer 
```
gst-launch-1.0 v4l2src device=/dev/video0 ! v4l2convert ! 'video/x-raw,format=(string)NV12,width=640,height=480,framerate=(fraction)25/1' ! queue ! v4l2h264enc ! h264parse ! flvmux ! rtmpsink location='rtmps://192.168.2.3:1936/live/stream0?user=user&pass=pass'
```
4. then I got server log like :
```
2023/08/08 15:43:18 INF [RTMP] [conn 192.168.2.3:49368] closed (EOF)
2023/08/08 15:43:28 INF [RTMPS] [conn 192.168.2.3:44632] opened
2023/08/08 15:43:28 INF [RTMPS] [conn 192.168.2.3:44632] closed (EOF)
```

5.  gstreamer log like :
```
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstRTMPSink:rtmpsink0: Could not open resource for writing.
Additional debug info:
gstrtmpsink.c(293): gst_rtmp_sink_render (): /GstPipeline:pipeline0/GstRTMPSink:rtmpsink0:
Could not connect to RTMP stream "rtmps://192.168.2.3:1936/live/stream0?user=user&pass=pass" for writing
Execution ended after 0:00:00.633439537
Setting pipeline to NULL ...
Freeing pipeline ...
ubuntu@ubuntu:~$ client_loop: send disconnect: Broken pipe
```

## Did you attach the server logs?

yes

## Did you attach a network dump?

no

**Comment by aler9** [comment] 2023-08-09 12:09
duplicate of #2186

**Closed by aler9** 2023-08-09 12:09 UTC

**Comment by renyongjian** [comment] 2023-08-09 12:58
I have try  gst-inspect-1.0 rtmpsink, It seems suppport rtmps.:
`URI handling capabilities:
  Element can act as sink.
  Supported URI protocols:
    rtmp
    rtmpt
    rtmps
    rtmpe
    rtmfp
    rtmpte
    rtmpts`

when I  push stream with   rtmp://uri/stream to rtmps  server , server logs  like "Not a TLS connection".
when I push stream with  rtmp:/uri/stream, server logs like "Opened ,but closed with EOF soon."

Is it related with CA?

**Comment by renyongjian** [comment] 2023-08-09 13:05
I run "gst-inspect-1.0 rtmpsink" cmd ,and  I got it support RTMPS
`URI handling capabilities:
  Element can act as sink.
  Supported URI protocols:
    rtmp
    rtmpt
    rtmps
    rtmpe
    rtmfp
    rtmpte
    rtmpts`

* when rtmpsink location='rtmp:uri' , server log  "2023/08/09 13:03:06 INF [RTMPS] [conn 192.168.2.3:56720] closed (tls: first record does not look like a TLS handshake)" 
* when rtmpsink location='rtmps:uri' ,server log "2023/08/09 13:03:49 INF [RTMPS] [conn 192.168.2.3:53424] closed (EOF)"
* they are different. I think rtmpsink support  rtmps.
*  because something other, server closed it soon with EOF.
