### ISSUE TITLE
Persistent configuration using API

### ISSUE THREAD

**Issue by leinad87** [bluenviron/mediamtx#1894] opened 2023-06-01 16:30 UTC
## Describe the feature

When a new stream is added using the API the cofiguration is stored on memory. Therefore, if the service is restarted, the stream configuration is lost. Do you think making API updates persistent on the config file is a good idea?

**Comment by aler9** [comment] 2023-06-02 11:15
duplicate of #1406

**Closed by aler9** 2023-06-02 11:15 UTC
