### ISSUE TITLE
Record ERR：too many reordered frames

### ISSUE THREAD

**Issue by klk2** [bluenviron/mediamtx#2513] opened 2023-10-16 02:34 UTC
## Which version are you using?

main

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

In a mac or window environment, when using rtsp://existing-url （another RTSP server / camera）, this exception is likely to occur during the recording process, which will cause the recording to stop.
This problem is more likely to occur when using WiFi instead of a network cable. Is it possible to keep the recording task from stopping?

## Describe how to replicate the issue

1. config:rtsp://existing-url -> the stream is pulled from another RTSP server / camera
2. start the server

## Did you attach the server logs?

```
2023/10/16 10:02:22 INF [WebRTC] listener opened on :8889 (HTTP)
2023/10/16 10:02:22 INF [SRT] listener opened on :8890 (UDP)
2023/10/16 10:02:22 INF [path stream0] [record] recording 1 track
2023/10/16 10:02:22 INF [path stream0] [RTSP source] ready: 1 track (H264)
2023/10/16 10:02:22 INF [path stream10] [record] recording 1 track
2023/10/16 10:02:22 INF [path stream10] [RTSP source] ready: 1 track (H264)
2023/10/16 10:02:22 INF [path stream2] [record] recording 1 track
2023/10/16 10:02:22 INF [path stream2] [RTSP source] ready: 1 track (H264)
2023/10/16 10:05:32 WAR [path stream0] [RTSP source] 141 RTP packets lost
2023/10/16 10:05:32 WAR [path stream10] [RTSP source] 131 RTP packets lost
2023/10/16 10:05:32 WAR [path stream2] [RTSP source] 25 RTP packets lost
2023/10/16 10:10:33 WAR [path stream10] [RTSP source] 88 RTP packets lost
2023/10/16 10:10:33 ERR [path stream10] [record] too many reordered frames (18)
2023/10/16 10:10:33 WAR [path stream2] [RTSP source] 12 RTP packets lost
2023/10/16 10:10:33 ERR [path stream2] [record] too many reordered frames (12)
2023/10/16 10:10:33 WAR [path stream0] [RTSP source] 36 RTP packets lost
2023/10/16 10:10:33 ERR [path stream0] [record] too many reordered frames (17)
2023/10/16 10:15:33 WAR [path stream10] [RTSP source] 165 RTP packets lost
2023/10/16 10:15:33 WAR [path stream0] [RTSP source] 144 RTP packets lost
2023/10/16 10:15:33 WAR [path stream2] [RTSP source] 112 RTP packets lost
2023/10/16 10:20:34 WAR [path stream0] [RTSP source] 158 RTP packets lost
2023/10/16 10:20:34 WAR [path stream10] [RTSP source] 162 RTP packets lost
2023/10/16 10:20:34 WAR [path stream2] [RTSP source] 10 RTP packets lost
2023/10/16 10:25:35 WAR [path stream2] [RTSP source] 77 RTP packets lost
2023/10/16 10:25:35 WAR [path stream2] invalid FU-A packet (non-starting)
2023/10/16 10:25:35 WAR [path stream10] [RTSP source] 138 RTP packets lost
2023/10/16 10:25:35 WAR [path stream0] [RTSP source] 131 RTP packets lost


```

## Did you attach a network dump?
no

**Comment by Sunvas** [comment] 2023-10-18 02:53
It also happens on OpenWRT in environment during recording RTSP stream from some of Dahua cams.

**Comment by aler9** [comment] 2023-10-24 18:33
duplicate of #2439

**Closed by aler9** 2023-10-24 18:33 UTC
