### ISSUE TITLE
Api authentication

### ISSUE THREAD

**Issue by Computershik73** [bluenviron/mediamtx#1769] opened 2023-05-05 15:56 UTC
## Describe the feature

Hi! I suggest to add authentication to the api, so that password and username will be required to get access to the list of streams.

**Comment by Computershik73** [comment] 2023-05-06 16:25
I have found the pull request that is still not merged... Why?

**Comment by aler9** [comment] 2023-05-31 09:57
duplicate of #1284

**Closed by aler9** 2023-05-31 09:57 UTC
