### ISSUE TITLE
hello can you make the reader of webrtc html , css dynamic

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [bluenviron/mediamtx#4053] opened 2024-12-18 10:30 UTC
### Describe the feature

instead of hard coded in the repository itself , is it possible to provide custom html and css to override the current ui ?

**Comment by asturl** [comment] 2024-12-18 12:59
There's nothing stopping you from making a completely custom html frontend that just connects a video element to the webrtc endpoint (using the javascript from the reader page as a guide)

Or do you explicitly want to restyle the page that opens when you go to a MediaMTX stream's webrtc webpage, without hosting anything else?

**Comment by MohamedKHALILRouissi** [comment] 2024-12-18 15:18
yes i want to use the base image for mediamtx , then use the ui ( html,css,js) as folder or link

**Comment by aler9** [comment] 2024-12-21 19:38
duplicate of #1229

**Closed by aler9** 2024-12-21 19:38 UTC
