### ISSUE TITLE
Config hot reloading in Docker

### ISSUE THREAD

**Issue by chris-adam-b12** [bluenviron/mediamtx#3547] opened 2024-07-11 09:58 UTC
## Which version are you using?

v1.8.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I'm using the dockerized version of MediaMTX with the config `mediamtx.yml` mounted from my laptop through a volume. When I change the config file, MediaMTX doesn't reload to take into account the changes as described in #109 

## Describe how to replicate the issue

1. `docker run --rm -v ./mediamtx.yml:/mediamtx.yml bluenviron/mediamtx:latest-ffmpeg`
2. Edit mediamtx.yml
3. Nothing is loaded without restarting the container

It also doesn't work without mounting the config file and just editing the file with vim from the inside of the container.

## Did you attach the server logs?

```
2024/07/11 09:57:41 INF MediaMTX v1.8.2
2024/07/11 09:57:41 INF configuration loaded from /mediamtx.yml
2024/07/11 09:57:41 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2024/07/11 09:57:41 INF [RTMP] listener opened on :1935
2024/07/11 09:57:41 INF [HLS] listener opened on :8888
2024/07/11 09:57:41 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
2024/07/11 09:57:41 INF [SRT] listener opened on :8890 (UDP)
```

## Did you attach a network dump?

no

**Comment by aler9** [comment] 2024-07-11 11:32
duplicate of #2661 - please use the search function before opening a new issue.

**Closed by aler9** 2024-07-11 11:32 UTC
