### ISSUE TITLE
Feature suggestion: runOnUnready

### ISSUE THREAD

**Issue by sgofferj** [bluenviron/mediamtx#1735] opened 2023-04-25 14:58 UTC
## Describe the feature

I'd like to suggest a runOnUnready configuration directive which triggers when a stream that was ready becomes unready, i.e. the publisher has stopped publishing to the path. The purpose for that would be to enable calls to webhooks or similar if a stream becomes unavailable, e.g.
```
runOnReady: curl -X POST -d "$RTSP_PATH" http://server/api/start
runOnUnready: curl -X POST -d "$RTSP_PATH" http://server/api/stop
```

**Comment by aler9** [comment] 2023-09-10 09:36
duplicate of #1464

**Closed by aler9** 2023-09-10 09:36 UTC
Labels: enhancement, general
