### ISSUE TITLE
Can mediamtx be used as a websocket singaling server?

### ISSUE THREAD

**Issue by zoujiaqing** [bluenviron/mediamtx#3977] opened 2024-11-25 11:18 UTC
### Describe the feature

I have an android project, I want use mediamtx as a media server to support webrtc.
I want use websocket instead of http to connect singnaling server.
Can mediamtx do that?

**Comment by aler9** [comment] 2024-12-04 23:44
duplicate of #3467

**Closed by aler9** 2024-12-04 23:44 UTC
