### ISSUE TITLE
no way to play stream with multicast?

### ISSUE THREAD

**Issue by ayhan9494** [bluenviron/mediamtx#2742] opened 2023-11-26 06:05 UTC
## Which version are you using?

v1.3.0

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
i try to use this tutorial -> https://github.com/bluenviron/mediamtx#vlc to run multicast but no way to use it.
This will be my final architectural image. All computers are connected to a Cisco switch. I want to broadcast the video of the camera through multicast without knowing the ip of the server system.
![untitled](https://github.com/bluenviron/mediamtx/assets/112747938/b3b129df-5fd9-42bf-80df-56e369586e18)

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

configfile:
[mediamtx.txt](https://github.com/bluenviron/mediamtx/files/13466029/mediamtx.txt)

**Comment by aler9** [comment] 2023-11-26 06:32
Duplicate of #2741

**Closed** 2023-11-26 06:33 UTC
