### ISSUE TITLE
RaspberryPi 5 Mediamtx Issues

### ISSUE THREAD

**Issue by xXAzazelXx** [bluenviron/mediamtx#3140] opened 2024-03-13 23:40 UTC
## Which version are you using?

v1.6.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [X] Linux arm64v8 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Launching the binary produces an error on RaspberyPi5 : 
`/dev/shm/rtspss-embeddedexe-1710372593620155793: error while loading shared libraries: libcamera.so.0.0: cannot open shared object file: No such file or directory`

## Describe how to replicate the issue

```
> libcamera-hello --list-cameras
Available cameras
-----------------
0 : imx219 [3280x2464 10-bit RGGB] (/base/axi/pcie@120000/rp1/i2c@88000/imx219@10)
    Modes: 'SRGGB10_CSI2P' : 640x480 [206.65 fps - (1000, 752)/1280x960 crop]
                             1640x1232 [41.85 fps - (0, 0)/3280x2464 crop]
                             1920x1080 [47.57 fps - (680, 692)/1920x1080 crop]
                             3280x2464 [21.19 fps - (0, 0)/3280x2464 crop]
           'SRGGB8' : 640x480 [206.65 fps - (1000, 752)/1280x960 crop]
                      1640x1232 [83.70 fps - (0, 0)/3280x2464 crop]
                      1920x1080 [47.57 fps - (680, 692)/1920x1080 crop]
                      3280x2464 [21.19 fps - (0, 0)/3280x2464 crop]
```

```
> uname -m
aarch64
```

```
> dpkg -l | grep libcamera0
ii  libcamera0.2:arm64                   0.2.0+rpt20240215-1                 arm64        complex camera support library
> dpkg -l | grep libfreetype6
ii  libfreetype6:arm64                   2.12.1+dfsg-5                       arm64        FreeType 2 font engine, shared library files
```

```
> ./mediamtx
2024/03/14 10:34:56 INF MediaMTX v1.6.0
2024/03/14 10:34:56 INF configuration loaded from /home/pi/Docker/mediamtx/mediamtx.yml
2024/03/14 10:34:56 INF [path cam] [RPI Camera source] started
2024/03/14 10:34:56 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2024/03/14 10:34:56 INF [RTMP] listener opened on :1935
2024/03/14 10:34:56 INF [HLS] listener opened on :8888
2024/03/14 10:34:56 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
2024/03/14 10:34:56 INF [SRT] listener opened on :8890 (UDP)
/dev/shm/rtspss-embeddedexe-1710372896047272268: error while loading shared libraries: libcamera.so.0.0: cannot open shared object file: No such file or directory

```
## Did you attach the server logs?

yes 

## Did you attach a network dump?

 no

## PS:

I have tried Docker deployment as well with the following config:

```
  cam:
    source: rpiCamera
    rpiCameraWidth: 1920
    rpiCameraHeight: 1080
    rpiCameraVFlip: true
    rpiCameraHFlip: true
```

```
[0:40:46.195230574] [486]  INFO Camera camera_manager.cpp:297 libcamera v0.0.5+83-bde9b04f
2024/03/12 21:01:36 ERR [path cam] [RPI Camera source] camera_create(): selected camera is not available
```

**Comment by aler9** [comment] 2024-03-14 14:23
duplicate of #2581

**Closed by aler9** 2024-03-14 14:23 UTC

**Comment by xXAzazelXx** [comment] 2024-08-10 07:06
omg , this worked for me https://gektor650.medium.com/comparing-video-stream-latencies-raspberry-pi-5-camera-v3-a8d5dad2f67b
