### ISSUE TITLE
Support for proxy prefix (i.e. "stripped path prefix") in webRTC

### ISSUE THREAD

**Issue by ijessen-mitll** [bluenviron/mediamtx#4042] opened 2024-12-13 03:27 UTC
### Describe the feature

When serving a resource behind a reversing proxy such as Traefik or NGINX, it's common to include path prefixes which are [stripped](https://doc.traefik.io/traefik/middlewares/http/stripprefix/) [by](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass:~:text=the%20part%20of%20a%20normalized%20request%20URI%20matching%20the%20location%20is%20replaced%20by%20a%20URI%20specified%20in%20the%20directive) the proxy prior to forwarding.  Doing so often requires the proxied service (i.e. mediamtx) to be aware of the stripped portion in order to properly link clients to resources.

One such example is the `Location` header in [mediamtx's response to a webRTC client's `whep` POST](https://github.com/bluenviron/mediamtx/blob/2d1a2da7b2c9e8da0bd9b09a854cafd4b4a3278f/internal/servers/webrtc/http_server.go#L232).  The client will subsequently PATCH to the location provided in this response header.  If the location doesn't properly reflect any stripped path prefixes, subsequent requests fail.

A configuration option to provide the stripped path prefix for use in the `Location` header (and potentially elsewhere) would allow for deployment behind path stripping reversing proxies.

[Here ](https://fastapi.tiangolo.com/advanced/behind-a-proxy/)is an example of a similar solution in FastAPI.

**Comment by aler9** [comment] 2024-12-15 12:00
Duplicate of #3649 - solution is in #3649.

**Closed by aler9** 2024-12-15 12:00 UTC
