### ISSUE TITLE
"closed: metadata doesn't contain any track" (DJI FlightHub Sync - Stream Forwarding)

### ISSUE THREAD

**Issue by JacekKosciesza** [bluenviron/mediamtx#3301] opened 2024-04-29 07:51 UTC
## Which version are you using?

v1.8.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I've a DJI Mavic 3E drone connected to [DJI FlightHub 2](https://enterprise.dji.com/flighthub-2) drone management platform. It has a new functionality [FlightHub Sync](https://fh.dji.com/user-manual/en/flighthub-sync/introduction.html#configure-stream-forwarding) which allows you to  transfer livestream data (stream forwarding) to a 3rd party using RTMP. I was able to initiate this stream forwarding to MediaMTX (running in Amazon Lightsail), but I get `closed: metadata doesn't contain any track` error.

2024/04/23 14:07:39 INF [RTMP] [conn 121.22.238.96:1219] opened
2024/04/23 14:07:40 DEB [path 1581F5FHD238P00DVX4S_66-0-0] created
2024/04/23 14:07:40 DEB [path 1581F5FHD238P00DVX4S_66-0-0] destroyed: not in use
2024/04/23 14:07:40 INF [RTMP] [conn 121.22.238.96:1219] closed: metadata doesn't contain any track 

## Describe how to replicate the issue

Replication is complicated - involves real DJI drone, configuration of DJI FlightHub 2 account, calling DJI API to start livestream etc. I will include logs and network dump, maybe someone will be able to verify on which side is a problem and maybe there is some workaround.  

## Did you attach the server logs?

yes

[mediamtx.log](https://github.com/bluenviron/mediamtx/files/15146359/mediamtx.log)

## Did you attach a network dump?

yes

[network_dump.pcap.zip](https://github.com/bluenviron/mediamtx/files/15146390/network_dump.pcap.zip)

**Comment by dbason** [comment] 2024-04-30 02:11
@JacekKosciesza we're also using mediamtx with the DJI Docks except in our case we're publishing direct from the dock to mediamtx using RTMP.  We haven't seen this issue so I suspect the problem is the republish from FlightHub.

**Comment by JacekKosciesza** [comment] 2024-05-06 13:27
I tried the same thing with [Ant Media Server](https://antmedia.io/docs/) and it worked. I was able to see the livestream from the drone:

<img width="1728" alt="ant-media-server-flghthub-sync" src="https://github.com/bluenviron/mediamtx/assets/8171434/0ae06916-e9c3-42a8-adfa-27ffd9e86d21">

**Comment by aler9** [comment] 2024-06-22 20:28
Hello, thanks for reporting the issue and providing the network dump. This should be fixed by #3504. Please try this nightly release (that contains #3504) and let me know if it fixes the issue:

https://github.com/bluenviron/mediamtx/actions/runs/9628106551

**Comment by aler9** [comment] 2024-07-01 14:03
since no one replied, i'm assuming it's fixed.A

**Closed** 2024-07-01 14:03 UTC
Labels: bug, rtmp
