### ISSUE TITLE
WebRTC AV1 publishing: Drop outs and browser support

### ISSUE THREAD

**Issue by zapf2000** [bluenviron/mediamtx#2005] opened 2023-06-30 09:44 UTC
## Which version are you using?

MediaMTX v0.0.0 (github Main clone 27.06.2023)

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When publishing with WebRTC publisher and receiving with WebRTC player, the video has drop outs every 2 seconds and video is not playable at Chome for Android. Works fine in the Linux Desktop version.

## Describe how to replicate the issue

Just use the following setup at WebRTC publisher and receive it via WebRTC player in a different tab or browser.

1. start the server

xxx@studio1:~/mediamtx$ ./mediamtx 
2023/06/30 11:37:06 INF MediaMTX v0.0.0
2023/06/30 11:37:06 DEB path manager created
2023/06/30 11:37:06 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/06/30 11:37:06 INF [RTMP] listener opened on :1935
2023/06/30 11:37:06 INF [HLS] listener opened on :8888
2023/06/30 11:37:06 INF [WebRTC] listener opened on :8889 (HTTP)
2023/06/30 11:37:06 INF [API] listener opened on 127.0.0.1:9997

2. publish with WebRTC publisher
[publish.txt](https://github.com/bluenviron/mediamtx/files/11915131/publish.txt)
![publish av1](https://github.com/bluenviron/mediamtx/assets/52130927/e77e1df2-7782-48a0-9fb9-f022810f008a)

3. read with WebRTC Player Chrome Desktop Linux
[receive chrome 114.0.5735.134 desktop linux.txt](https://github.com/bluenviron/mediamtx/files/11915150/receive.chrome.114.0.5735.134.desktop.linux.txt)

with Chrome Android
[receive chrome 114.0.5735.130 android.txt](https://github.com/bluenviron/mediamtx/files/11915154/receive.chrome.114.0.5735.130.android.txt)

And a video of it, showing the dropouts every 2 seconds

https://github.com/bluenviron/mediamtx/assets/52130927/d1d3802c-4c84-4d8a-b8e0-13197fd9113a

## Did you attach the server logs?

yes 

## Did you attach a network dump?

no

**Comment by aler9** [comment] 2023-10-06 20:25
Hello, regarding Android, from the logs it's clear that the smartphone you used to perform the test doesn't support decoding AV1.

Regarding Linux, stuttering is caused by the fact that your PC is is too slow in decoding AV1 - Chrome detects the delay and discards frames. This is a duplicate of #1697 and can be solved by adding a flag that introduces latency.

**Closed** 2023-10-06 20:28 UTC

**Comment by zapf2000** [comment] 2023-10-06 20:45
No, aler9, it works perfect now... sorry i didn't close
