### ISSUE TITLE
Change served WebRTC files without recompiling 

### ISSUE THREAD

**Issue by destenson** [bluenviron/mediamtx#3321] opened 2024-05-05 01:11 UTC
## Describe the feature

Description

Afaik, MediaMTX serves static web pages and scripts to clients of the WebRTC server. I'd like to be able to modify them without recompiling MediaMTX. This could be via specifying files by a command line argument or in the config file or by an API call. Is that possible today or does that feature need to be implemented?

**Comment by aler9** [comment] 2024-05-05 08:46
duplicate of #2649

**Closed by aler9** 2024-05-05 08:46 UTC
